const router = require('express').Router()
const healthController = require('../controllers/healthController')
const { authMiddleware } = require('../middleware/authMiddleware')

router.get('/', healthController.root)
router.get('/health', healthController.health)
router.get('/api/health', healthController.health)
router.use('/dashboard', authMiddleware, require('./dashboardRoutes'))
router.use('/inventory', authMiddleware, require('./inventoryRoutes'))
router.use('/purchases', authMiddleware, require('./purchaseRoutes'))
router.use('/sales', authMiddleware, require('./saleRoutes'))
router.use('/reports', authMiddleware, require('./reportRoutes'))
router.use('/settings', authMiddleware, require('./settingsRoutes'))
router.use('/search', authMiddleware, require('./searchRoutes'))
router.use('/venues', authMiddleware, require('./venueRoutes'))
router.use('/expenses', authMiddleware, require('./expenseRoutes'))
router.use('/stock-movements', authMiddleware, require('./stockMovementRoutes'))
router.use('/loans', authMiddleware, require('./loanRoutes'))
router.use('/auth', require('./authRoutes'))
router.use('/api/dashboard', authMiddleware, require('./dashboardRoutes'))
router.use('/api/inventory', authMiddleware, require('./inventoryRoutes'))
router.use('/api/purchases', authMiddleware, require('./purchaseRoutes'))
router.use('/api/sales', authMiddleware, require('./saleRoutes'))
router.use('/api/reports', authMiddleware, require('./reportRoutes'))
router.use('/api/settings', authMiddleware, require('./settingsRoutes'))
router.use('/api/search', authMiddleware, require('./searchRoutes'))
router.use('/api/venues', authMiddleware, require('./venueRoutes'))
router.use('/api/expenses', authMiddleware, require('./expenseRoutes'))
router.use('/api/stock-movements', authMiddleware, require('./stockMovementRoutes'))
router.use('/api/loans', authMiddleware, require('./loanRoutes'))
router.use('/api/auth', require('./authRoutes'))

module.exports = router
