const router = require('express').Router()
const healthController = require('../controllers/healthController')
const { authMiddleware } = require('../middleware/authMiddleware')
const { shopFeatureMiddleware } = require('../middleware/shopFeatureMiddleware')

router.get('/', healthController.root)
router.get('/health', healthController.health)
router.get('/api/health', healthController.health)
router.use('/dashboard', authMiddleware, shopFeatureMiddleware('dashboard'), require('./dashboardRoutes'))
router.use('/inventory', authMiddleware, shopFeatureMiddleware('inventory'), require('./inventoryRoutes'))
router.use('/purchases', authMiddleware, shopFeatureMiddleware('purchases'), require('./purchaseRoutes'))
router.use('/sales', authMiddleware, shopFeatureMiddleware('sales'), require('./saleRoutes'))
router.use('/reports', authMiddleware, shopFeatureMiddleware('reports'), require('./reportRoutes'))
router.use('/settings', authMiddleware, shopFeatureMiddleware('settings'), require('./settingsRoutes'))
router.use('/search', authMiddleware, shopFeatureMiddleware('search'), require('./searchRoutes'))
router.use('/venues', authMiddleware, shopFeatureMiddleware('venues'), require('./venueRoutes'))
router.use('/expenses', authMiddleware, shopFeatureMiddleware('expenses'), require('./expenseRoutes'))
router.use('/stock-movements', authMiddleware, shopFeatureMiddleware('stock-movements'), require('./stockMovementRoutes'))
router.use('/loans', authMiddleware, shopFeatureMiddleware('loans'), require('./loanRoutes'))
router.use('/transfers', authMiddleware, shopFeatureMiddleware('transfers'), require('./partnerTransferRoutes'))
router.use('/shop/users', authMiddleware, require('./shopUserRoutes'))
router.use('/admin', authMiddleware, require('./adminRoutes'))
router.use('/auth', require('./authRoutes'))
router.use('/api/dashboard', authMiddleware, shopFeatureMiddleware('dashboard'), require('./dashboardRoutes'))
router.use('/api/inventory', authMiddleware, shopFeatureMiddleware('inventory'), require('./inventoryRoutes'))
router.use('/api/purchases', authMiddleware, shopFeatureMiddleware('purchases'), require('./purchaseRoutes'))
router.use('/api/sales', authMiddleware, shopFeatureMiddleware('sales'), require('./saleRoutes'))
router.use('/api/reports', authMiddleware, shopFeatureMiddleware('reports'), require('./reportRoutes'))
router.use('/api/settings', authMiddleware, shopFeatureMiddleware('settings'), require('./settingsRoutes'))
router.use('/api/search', authMiddleware, shopFeatureMiddleware('search'), require('./searchRoutes'))
router.use('/api/venues', authMiddleware, shopFeatureMiddleware('venues'), require('./venueRoutes'))
router.use('/api/expenses', authMiddleware, shopFeatureMiddleware('expenses'), require('./expenseRoutes'))
router.use('/api/stock-movements', authMiddleware, shopFeatureMiddleware('stock-movements'), require('./stockMovementRoutes'))
router.use('/api/loans', authMiddleware, shopFeatureMiddleware('loans'), require('./loanRoutes'))
router.use('/api/transfers', authMiddleware, shopFeatureMiddleware('transfers'), require('./partnerTransferRoutes'))
router.use('/api/shop/users', authMiddleware, require('./shopUserRoutes'))
router.use('/api/admin', authMiddleware, require('./adminRoutes'))
router.use('/api/auth', require('./authRoutes'))

module.exports = router
