const router = require('express').Router()
const healthController = require('../controllers/healthController')

router.get('/', healthController.root)
router.get('/health', healthController.health)
router.get('/api/health', healthController.health)
router.use('/dashboard', require('./dashboardRoutes'))
router.use('/inventory', require('./inventoryRoutes'))
router.use('/purchases', require('./purchaseRoutes'))
router.use('/sales', require('./saleRoutes'))
router.use('/reports', require('./reportRoutes'))
router.use('/settings', require('./settingsRoutes'))
router.use('/search', require('./searchRoutes'))
router.use('/venues', require('./venueRoutes'))
router.use('/expenses', require('./expenseRoutes'))
router.use('/stock-movements', require('./stockMovementRoutes'))
router.use('/loans', require('./loanRoutes'))
router.use('/api/dashboard', require('./dashboardRoutes'))
router.use('/api/inventory', require('./inventoryRoutes'))
router.use('/api/purchases', require('./purchaseRoutes'))
router.use('/api/sales', require('./saleRoutes'))
router.use('/api/reports', require('./reportRoutes'))
router.use('/api/settings', require('./settingsRoutes'))
router.use('/api/search', require('./searchRoutes'))
router.use('/api/venues', require('./venueRoutes'))
router.use('/api/expenses', require('./expenseRoutes'))
router.use('/api/stock-movements', require('./stockMovementRoutes'))
router.use('/api/loans', require('./loanRoutes'))

module.exports = router
